/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTemasRouteImport } from './routes/admin.temas'
import { Route as AdminOradoresRouteImport } from './routes/admin.oradores'
import { Route as AdminCongregacoesRouteImport } from './routes/admin.congregacoes'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemasRoute = AdminTemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOradoresRoute = AdminOradoresRouteImport.update({
  id: '/oradores',
  path: '/oradores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCongregacoesRoute = AdminCongregacoesRouteImport.update({
  id: '/congregacoes',
  path: '/congregacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/congregacoes': typeof AdminCongregacoesRoute
  '/admin/oradores': typeof AdminOradoresRoute
  '/admin/temas': typeof AdminTemasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/congregacoes': typeof AdminCongregacoesRoute
  '/admin/oradores': typeof AdminOradoresRoute
  '/admin/temas': typeof AdminTemasRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/congregacoes': typeof AdminCongregacoesRoute
  '/admin/oradores': typeof AdminOradoresRoute
  '/admin/temas': typeof AdminTemasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/agenda'
    | '/admin/congregacoes'
    | '/admin/oradores'
    | '/admin/temas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/agenda'
    | '/admin/congregacoes'
    | '/admin/oradores'
    | '/admin/temas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/agenda'
    | '/admin/congregacoes'
    | '/admin/oradores'
    | '/admin/temas'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/temas': {
      id: '/admin/temas'
      path: '/temas'
      fullPath: '/admin/temas'
      preLoaderRoute: typeof AdminTemasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/oradores': {
      id: '/admin/oradores'
      path: '/oradores'
      fullPath: '/admin/oradores'
      preLoaderRoute: typeof AdminOradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/congregacoes': {
      id: '/admin/congregacoes'
      path: '/congregacoes'
      fullPath: '/admin/congregacoes'
      preLoaderRoute: typeof AdminCongregacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminCongregacoesRoute: typeof AdminCongregacoesRoute
  AdminOradoresRoute: typeof AdminOradoresRoute
  AdminTemasRoute: typeof AdminTemasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminCongregacoesRoute: AdminCongregacoesRoute,
  AdminOradoresRoute: AdminOradoresRoute,
  AdminTemasRoute: AdminTemasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
